In [6]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\eilee\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [19]:
# --- 3.1 1D NumPy Arrays ---

In [5]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

In [9]:
print("Multiplied by 4:", arr * 4)

Multiplied by 4: [ 80 108  36  48 124  68  16 200 156 140]


In [8]:
print("Mean:", np.mean(arr))

Mean: 24.4


In [10]:
print("Median:", np.median(arr))

Median: 23.5


In [11]:
print("Standard Deviation:", np.std(arr))

Standard Deviation: 13.828955130450023


In [12]:
print(f"Index of smallest: {np.argmin(arr)}, Index of largest: {np.argmax(arr)}")

Index of smallest: 6, Index of largest: 7


In [14]:
print(f"Value at min_index: {arr[np.argmin(arr)]}")
print(f"Value at max_index: {arr[np.argmax(arr)]}")

Value at min_index: 4
Value at max_index: 50


In [15]:
print(f"Smallest value: {np.min(arr)}, Largest value: {np.max(arr)}")

Smallest value: 4, Largest value: 50


In [17]:
print("Do they match?", arr[np.argmin(arr)] == np.min(arr) and arr[np.argmax(arr)] == np.max(arr))

Do they match? True


In [18]:
print("Values greater than 20:", arr[arr > 20])

Values greater than 20: [27 31 50 39 35]


In [20]:
# --- 3.2 2D NumPy Arrays ---

In [21]:
matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])

In [23]:
shape = matrix.shape
print(f"Shape: {shape}")
print(f"Rows: {shape[0]}, Columns: {shape[1]}")

Shape: (3, 4)
Rows: 3, Columns: 4


In [25]:
print("Third column:", matrix[:, 2])

Third column: [17 14 19]


In [26]:
print("Second row:", matrix[1, :])

Second row: [ 8 21 14  3]


In [28]:
print("Multiplied by 2:\n", matrix * 2)

Multiplied by 2:
 [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [30]:
print("Mean of each column:", np.mean(matrix, axis=1))
                                      

Mean of each column: [10.75 11.5  12.25]


In [31]:
print("Overall mean:", np.mean(matrix))

Overall mean: 11.5


In [32]:
print("Max in each row:", np.max(matrix, axis=1))
print("Min in each column:", np.min(matrix, axis=0))

Max in each row: [17 21 19]
Min in each column: [ 5 12 14  3]


In [37]:
flat_matrix = matrix.flatten()
print("Flattened shape:", flat_matrix)
# The 2D array was collapsed into a single 1D array of 12 elements

Flattened shape: [ 5 12 17  9  8 21 14  3  6 13 19 11]


In [40]:
min_idx_flat = np.argmin(matrix)
max_idx_flat = np.argmax(matrix)
print(f"Flat matrix - Smallest Index: {min_idx_flat}, Largest Index: {max_idx_flat}")

Flat matrix - Smallest Index: 7, Largest Index: 5


In [46]:
min_coords = np.unravel_index(min_idx_flat, matrix.shape)
max_coords = np.unravel_index(max_idx_flat, matrix.shape)
print(f"Flat matrix - Smallest Coordinates: {min_coords}, Largest Coordinates: {max_coords}")

Flat matrix - Smallest Coordinates: (np.int64(1), np.int64(3)), Largest Coordinates: (np.int64(1), np.int64(1))


In [47]:
print("Values > 15:", matrix[matrix > 15])

Values > 15: [17 21 19]


In [49]:
print("Sorted each row:\n", np.sort(matrix, axis=1))

Sorted each row:
 [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [50]:
# --- Prime Star Systems ---

In [58]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

In [59]:
def is_prime(n):
    if n < 2: 
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [64]:
def get_prime_rows(data):
    v_is_prime = np.vectorize(is_prime)
    prime_mask = v_is_prime(data)
    rows_with_primes = np.any(prime_mask, axis=1)
    return data[rows_with_primes]

In [66]:
prime_star_systems = get_prime_rows(arr)
print("Star systems >= 1 prime magnitude:\n", prime_star_systems)

Star systems >= 1 prime magnitude:
 [[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [67]:
# --- 5 Let’s Play Checkers! ---

In [74]:
def checkerboard():
   # 5.1
    board = np.zeros((8,8), dtype = int)

    # 5.2
    board[0::2, 0::2] = 1

    # 5.3
    board[1::2, 1::2] = 1
    
    return board

In [80]:
print("Standard Checkerboard:")
print(checkerboard())

Standard Checkerboard:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [79]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[0::2, 1::2] = 1
    board[1::2, 0::2] = 1
    return board

In [81]:
print("Reverse Checkerboard:")
print(reverse_checkerboard())

Reverse Checkerboard:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [82]:
# --- 6 The Expanding Universe ---

In [91]:
def expansion(arr, n):
    def add_spaces(s):
        spacer = " " * n
        return spacer.join(s)
    
    v_expansion = np.vectorize(add_spaces)
    
    return v_expansion(arr)

In [93]:
universe = np.array(['galaxy', 'clusters'])
print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [94]:
# --- 7 Second-Brightest Star ---

In [103]:
def second_brightest(data):
    sorted_stars = np.sort(data, axis=1)
    return sorted_stars[:, -2]

In [104]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))

In [106]:
result = second_brightest(stars)
print("Star Clusters:\n", stars)
print("\nSecond Brightest stars:", result)

Star Clusters:
 [[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]

Second Brightest stars: [1889 1647 1138 1863 1592]
